// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFiles():Promise<Array<string>>;

export function GetFolders():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;
